# NYPL Travis Travis

language: node_js
node_js:
  - 6
install:
  - gem install jekyll bundler
  - npm install
before_script:
  - cd ./docs
  - bundle install
  - bundle exec jekyll serve --detach
script: npm run test-pa11y
cache:
  directories:
    - "node_modules"
