# matrix:
#   include:
#     language: ruby
#     cache: bundler
#     before_script:
#       - cd ./docs
#     script:
#       - bundle install
#
#   include:
language: node_js
node_js:
  - 6
install:
  - gem install jekyll bundler
  - npm install
before_script:
    - cd ./docs
    - bundle install
    - bundle exec jekyll serve
script: npm run test-pa11y
cache:
  directories:
    - "node_modules"
