baseurl: ''

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

scope:
  path: "_sections/icons"
values:
  icon: true

collections:
  sections:
    output: true
  resources:
    output: true

exclude:
  - Gemfile
  - README.md
