baseurl: "/design-toolkit"

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

collections:
  sections:
    output: true
  resources:
    output: true
  blogs:
    output: true

exclude:
  - Gemfile
  - README.md

#custom variables
current-version: 0.1.31
